name: ota_update
description: A Flutter plugin providing ota updates for Android and iOS, with download progress (Android only)
version: 5.1.0
homepage: https://github.com/4Q-s-r-o/ota_update

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.13+hotfix.6"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: sk.fourq.otaupdate
        pluginClass: OtaUpdatePlugin
